/**
 * Generate src/weather-icons.generated.ts from a checkout of metno/weathericons.
 *
 * The card used to fetch all 83 icons from raw.githubusercontent.com on every render.
 * That is a hard network dependency for something that never changes, and it fails in
 * three ways seen in practice: GitHub rate-limits a busy or shared IP (429/503, after
 * which the icons silently vanish), a TLS-inspecting corporate proxy breaks the fetch,
 * and it simply does not work offline.
 *
 * Raw they are 279 KB, but they share their <symbol> and gradient definitions across the
 * day/night/polartwilight variants and compress about 46:1 — roughly 6 KB gzipped, which
 * is what actually crosses the wire since Home Assistant serves compressed.
 *
 *   git clone --depth 1 https://github.com/metno/weathericons /tmp/weathericons
 *   node tools/build-icons.mjs /tmp/weathericons/weather/svg
 *
 * Icons are MIT licensed by the Norwegian Meteorological Institute.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const src = process.argv[2];
if (!src) {
  console.error("usage: node tools/build-icons.mjs <path to weathericons/weather/svg>");
  process.exit(2);
}

const out = resolve(import.meta.dirname, "../src/weather-icons.generated.ts");
const files = readdirSync(src).filter((f) => f.endsWith(".svg")).sort();
if (!files.length) {
  console.error(`no .svg files in ${src}`);
  process.exit(1);
}

/** Collapse the indentation the source files ship with; it is pure payload here. */
const squeeze = (svg) =>
  svg.replace(/\r?\n\s*/g, "").replace(/>\s+</g, "><").trim();

let raw = 0;
const entries = files.map((f) => {
  const body = readFileSync(join(src, f), "utf8");
  raw += body.length;
  const name = f.replace(/\.svg$/, "");
  // JSON.stringify handles the quoting and escaping correctly, including any unicode.
  return `  ${JSON.stringify(name)}: ${JSON.stringify(squeeze(body))},`;
});

const banner = `// Generated by tools/build-icons.mjs — do not edit by hand.
//
// Weather icons from https://github.com/metno/weathericons, MIT licensed by the
// Norwegian Meteorological Institute.
//
// Bundled rather than fetched: the card previously pulled every icon from
// raw.githubusercontent.com on each render, which breaks when GitHub rate-limits a
// shared IP, when a TLS-inspecting proxy sits in the way, and whenever the browser is
// offline. Large in source but highly compressible — these share their symbol and
// gradient definitions, so the set is a few KB on the wire.
//
// ${files.length} icons, ${(raw / 1024).toFixed(0)} KB of source SVG.

export const WEATHER_ICONS: Readonly<Record<string, string>> = Object.freeze({
`;

writeFileSync(out, banner + entries.join("\n") + "\n});\n", "utf8");
const written = readFileSync(out, "utf8").length;
console.log(`wrote ${out}`);
console.log(`  ${files.length} icons, ${(raw / 1024).toFixed(0)} KB source -> ${(written / 1024).toFixed(0)} KB module`);
