/**
 * Write src/build-version.generated.ts so the card can report the build it came from.
 *
 * package.json carries 2026.8.3 whether the build came from v2026.8.3 or v2026.8.3-beta2,
 * so the card showed the same number for a release and every prerelease of it. That is
 * exactly the wrong time to be vague: asking someone in a support thread to confirm they
 * have the new build only works if the card can tell them.
 *
 * With RELEASE_TAG set — the workflow passes github.ref_name — the tag wins, minus its
 * leading v: a published artefact is identified by its tag. Without it the value is
 * package.json's version, so a local build writes the same file that is committed and
 * leaves no diff behind.
 *
 *   node tools/stamp-version.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const tag = (process.env.RELEASE_TAG ?? "").trim().replace(/^v/, "");
const version = tag || pkg.version;

const out = join(ROOT, "src/build-version.generated.ts");
const body = `// Generated by tools/stamp-version.mjs — do not edit by hand.
//
// The build this bundle came from. Equal to package.json's version for a local or
// untagged build, and to the release tag when the workflow sets RELEASE_TAG — so a
// prerelease reports "2026.8.3-beta2" rather than the "2026.8.3" it shares with the
// release.

export const BUILD_VERSION = ${JSON.stringify(version)};
`;

const existing = (() => { try { return readFileSync(out, "utf8"); } catch { return ""; } })();
if (existing !== body) {
  writeFileSync(out, body, "utf8");
  console.log(`stamped ${version}`);
} else {
  console.log(`version unchanged (${version})`);
}
