/**
 * Write src/build-version.generated.ts so the card can report the build it came from.
 *
 * package.json carries 2026.8.3 whether the build came from v2026.8.3 or v2026.8.3-beta2,
 * so the card showed the same number for a release and every prerelease of it. That is
 * exactly the wrong time to be vague: asking someone in a support thread to confirm they
 * have the new build only works if the card can tell them.
 *
 * With RELEASE_TAG set — the workflow passes github.ref_name — the tag wins, minus its
 * leading v: a published artefact is identified by its tag. Any other build is one
 * someone made and uploaded by hand, so it carries the commit instead, and says .dirty
 * when the tree had uncommitted changes. The generated file is not committed, since it
 * changes with every commit.
 *
 *   node tools/stamp-version.mjs
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

/** Short sha of HEAD, with .dirty when the tree has uncommitted changes. */
function commitStamp() {
  try {
    const sha = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
      encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    const dirty = execFileSync("git", ["status", "--porcelain"], {
      encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
    }).trim().length > 0;
    return sha ? `${sha}${dirty ? ".dirty" : ""}` : "";
  } catch {
    return "";
  }
}

const ROOT = resolve(import.meta.dirname, "..");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const tag = (process.env.RELEASE_TAG ?? "").trim().replace(/^v/, "");
const commit = commitStamp();
// A tagged build says the tag and nothing else — that is a published artefact and its
// identity is the tag. Anything else is a build someone made and uploaded by hand, and
// what matters then is which commit it came from, so it carries the sha. Same shape as
// the mspa integration's +hot.<sha>, which is already what gets read every day.
const version = tag || (commit ? `${pkg.version}+hot.${commit}` : pkg.version);

const out = join(ROOT, "src/build-version.generated.ts");
const body = `// Generated by tools/stamp-version.mjs — do not edit by hand.
//
// The build this bundle came from. Equal to package.json's version for a local or
// untagged build, and to the release tag when the workflow sets RELEASE_TAG — so a
// prerelease reports "2026.8.3-beta2" rather than the "2026.8.3" it shares with the
// release.

export const BUILD_VERSION = ${JSON.stringify(version)};
`;

writeFileSync(out, body, "utf8");
console.log(`stamped ${version}`);
