/**
 * Write src/build-version.generated.ts so the card can report the build it came from.
 *
 * package.json carries 2026.8.3 whether the build came from v2026.8.3 or v2026.8.3-beta2,
 * so the card showed the same number for a release and every prerelease of it. That is
 * exactly the wrong time to be vague: asking someone in a support thread to confirm they
 * have the new build only works if the card can tell them.
 *
 * With RELEASE_TAG set — the workflow passes github.ref_name — the tag wins, minus its
 * leading v: a published artefact is identified by its tag.
 *
 * Without it the build is local, and gets package.json's version with the commit
 * appended: "2026.8.3+hot.9a50494", plus ".dirty" if anything was uncommitted. That is
 * so a hand-uploaded bundle can be identified without cutting a prerelease for it —
 * which is otherwise the only way to tell two builds of the same version apart, and a
 * poor reason to publish. The generated file is not committed, so this leaves no diff.
 *
 *   node tools/stamp-version.mjs
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const tag = (process.env.RELEASE_TAG ?? "").trim().replace(/^v/, "");

/** The commit this tree is on, and whether anything is uncommitted. */
function git() {
  const run = (...args) =>
    execFileSync("git", args, { cwd: ROOT, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  try {
    return { sha: run("rev-parse", "--short", "HEAD"),
             dirty: run("status", "--porcelain").length > 0 };
  } catch {
    return null;                       // not a checkout, or no git — fall back quietly
  }
}

let version = tag;
if (!version) {
  const g = git();
  version = g
    ? `${pkg.version}+hot.${g.sha}${g.dirty ? ".dirty" : ""}`
    : pkg.version;
}

const out = join(ROOT, "src/build-version.generated.ts");
const body = `// Generated by tools/stamp-version.mjs — do not edit by hand, and not committed.
//
// The build this bundle came from.
//
//   released    the tag the workflow passed as RELEASE_TAG, minus its v, so a
//               prerelease reports "2026.8.3-beta2" and not the "2026.8.3" it shares
//               with the release
//   local       "2026.8.3+hot.9a50494", naming the commit the bundle was built from,
//               with ".dirty" appended when the tree had uncommitted changes
//
// The local form exists so a hand-uploaded dist/meteogram-card.js can be identified
// without cutting a prerelease for it. It is build metadata in the semver sense — after
// a "+" — which is ignored for ordering, so nothing compares a hot build against a
// release and offers a downgrade.

export const BUILD_VERSION = ${JSON.stringify(version)};
`;

const existing = (() => { try { return readFileSync(out, "utf8"); } catch { return ""; } })();
if (existing !== body) {
  writeFileSync(out, body, "utf8");
  console.log(`stamped ${version}`);
} else {
  console.log(`version unchanged (${version})`);
}
