// Generated by tools/stamp-version.mjs — do not edit by hand.
//
// The build this bundle came from. Equal to package.json's version for a local or
// untagged build, and to the release tag when the workflow sets RELEASE_TAG — so a
// prerelease reports "2026.8.3-beta2" rather than the "2026.8.3" it shares with the
// release.

export const BUILD_VERSION = "2026.8.3";
