// Generated by tools/stamp-version.mjs — do not edit by hand, and not committed.
//
// The build this bundle came from.
//
//   released    the tag the workflow passed as RELEASE_TAG, minus its v, so a
//               prerelease reports "2026.8.3-beta2" and not the "2026.8.3" it shares
//               with the release
//   local       "2026.8.3+hot.9a50494", naming the commit the bundle was built from,
//               with ".dirty" appended when the tree had uncommitted changes
//
// The local form exists so a hand-uploaded dist/meteogram-card.js can be identified
// without cutting a prerelease for it. It is build metadata in the semver sense — after
// a "+" — which is ignored for ordering, so nothing compares a hot build against a
// release and offers a downgrade.

export const BUILD_VERSION = "2026.8.3+hot.9a50494.dirty";
